### ISSUE TITLE
3 errors right after loading the scene

### ISSUE THREAD

**Issue by Kashrlyyk** [alhaddado/unity-scrolly#1]
Unity Version 4.6.0f3

Assets/ScrollListTest.cs(27,44): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for`value' and no extension method `value' of type`UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

Assets/ScrollListTest.cs(27,21): error CS1502: The best overloaded method match for `int.TryParse(string, out int)' has some invalid arguments

Assets/ScrollListTest.cs(27,21): error CS1503: Argument `#1' cannot convert`object' expression to type `string'

**Comment by alhaddado** [comment]
Fixed
