### ISSUE TITLE
Example do not work

### ISSUE THREAD

**Issue by jeanfabre** [alhaddado/unity-scrolly#3]
Hi,

 It's odd, the sample scene doesn't do anything when I click on Create. Is there any particular setup or things to do prior playing the scene?

Thanks,

 Jean

**Comment by alhaddado** [comment]
@jeanfabre Hi Jean. You need to specify the number of cells to be created in the text box next to the create button

**Comment by jeanfabre** [comment]
Ah! :) I was putting a text expecting to create a cell with that text!

 it works now, thanks!

 Jean
